export const EDIT_CONFIRM_TRANSFER_POPUP_FIELD = Symbol('EDIT_CONFIRM_TRANSFER_POPUP_FIELD');
export const RESET_CONFIRM_TRANSFER_POPUP_STATE = Symbol('RESET_CONFIRM_TRANSFER_POPUP_STATE');
export const SET_CONRIFM_TRANSFER_POPUP_ERRORS = Symbol('SET_CONFIRM_TRANSFER_POPUP_ERRORS');
