export const SET_ACTIVE_TAB = Symbol('SET_ACTIVE_TAB');
export const GET_SCREEN_CONFIGURATION = Symbol('GET_SCREEN_CONFIGURATION');
export const FETCH_CUSTOMER_DATA = Symbol('FETCH_CUSTOMER_DATA');
export const FETCH_ACCOUNTS = Symbol('FETCH_ACCOUNTS');
export const CREATE_TRANSFER = Symbol('CREATE_TRANSFER');
export const EDIT_TRANSFER_FIELD = Symbol('EDIT_FIELD');
